version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: heart-disease-prediction-api
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - MODEL_DIR=/app/models
      - LOG_LEVEL=INFO
    restart: unless-stopped
    command: ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
