version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: heart-disease-prediction-api-prod
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./config:/app/config
      - /var/backups/heart-disease-mlp:/app/backups
    environment:
      # Core settings
      - MODEL_DIR=/app/models
      - ENVIRONMENT=prod
      - LOG_LEVEL=WARNING

      # Authentication settings - these should be set via environment variables in production
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

      # Backup settings
      - BACKUP_FREQUENCY=hourly
      - KEEP_BACKUPS=24
      - CLOUD_BACKUP=true
      - CLOUD_PROVIDER=s3
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
    restart: always
    command: ["python", "run_api.py", "--host", "0.0.0.0", "--port", "8000"]

  backup:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: heart-disease-prediction-backup-prod
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./config:/app/config
      - /var/backups/heart-disease-mlp:/app/backups
    environment:
      - ENVIRONMENT=prod
      - BACKUP_FREQUENCY=hourly
      - KEEP_BACKUPS=24
      - CLOUD_BACKUP=true
      - CLOUD_PROVIDER=s3
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
    restart: always
    command: ["python", "scripts/scheduled_backup.py", "--cloud"]
