version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: heart-disease-prediction-api-staging
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./config:/app/config
      - ./backups:/app/backups
    environment:
      # Core settings
      - MODEL_DIR=/app/models
      - ENVIRONMENT=staging
      - LOG_LEVEL=INFO

      # Authentication settings
      - JWT_SECRET_KEY=staging_secret_key_for_testing_only

      # Backup settings
      - BACKUP_FREQUENCY=daily
      - KEEP_BACKUPS=10
      - CLOUD_BACKUP=true
      - CLOUD_PROVIDER=s3
      - AWS_ACCESS_KEY_ID=your_staging_aws_access_key
      - AWS_SECRET_ACCESS_KEY=your_staging_aws_secret_key
      - AWS_BUCKET_NAME=your-staging-bucket
    restart: unless-stopped
    command: ["python", "run_api.py", "--host", "0.0.0.0", "--port", "8000"]

  backup:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: heart-disease-prediction-backup-staging
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./config:/app/config
      - ./backups:/app/backups
    environment:
      - ENVIRONMENT=staging
      - BACKUP_FREQUENCY=daily
      - KEEP_BACKUPS=10
      - CLOUD_BACKUP=true
      - CLOUD_PROVIDER=s3
      - AWS_ACCESS_KEY_ID=your_staging_aws_access_key
      - AWS_SECRET_ACCESS_KEY=your_staging_aws_secret_key
      - AWS_BUCKET_NAME=your-staging-bucket
    restart: unless-stopped
    command: ["python", "scripts/scheduled_backup.py", "--cloud"]
