version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: heart-disease-prediction-api-dev
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./config:/app/config
      - ./backups:/app/backups
    environment:
      # Core settings
      - MODEL_DIR=/app/models
      - ENVIRONMENT=dev
      - LOG_LEVEL=DEBUG
      
      # Authentication settings
      - JWT_SECRET_KEY=dev_secret_key_1234567890
      
      # Backup settings
      - BACKUP_FREQUENCY=daily
      - KEEP_BACKUPS=5
      - CLOUD_BACKUP=false
    restart: unless-stopped
    command: ["python", "run_api.py", "--host", "0.0.0.0", "--port", "8000", "--reload"]