# Project Configuration

# Data paths
data:
  raw_data_path: 'data/raw/heart_disease_combined.csv'
  processed_data_path: 'data/processed/heart_disease_processed.csv'
  external_data_path: 'data/external/medical_reference_data.csv'

# Feature engineering
preprocessing:
  categorical_features:
    - 'sex'
    - 'cp'
    - 'fbs'
    - 'restecg'
    - 'exang'
    - 'slope'
    - 'ca'
    - 'thal'
  numerical_features:
    - 'age'
    - 'trestbps'
    - 'chol'
    - 'thalach'
    - 'oldpeak'
  target: 'target'
  test_size: 0.2
  validation_size: 0.25
  random_seed: 42

# Model parameters
model:
  mlp:
    hidden_layer_sizes: [100, 50]
    activation: 'relu'
    solver: 'adam'
    alpha: 0.0001
    learning_rate_init: 0.001
    max_iter: 2000
    random_state: 42
  advanced_mlp:
    architecture:
      - {units: 128, activation: 'leaky_relu', dropout: 0.3, l2_regularization: 0.01}
      - {units: 64, activation: 'leaky_relu', dropout: 0.3, l2_regularization: 0.01}
      - {units: 32, activation: 'leaky_relu', dropout: 0.2, l2_regularization: 0.01}
    batch_size: 32
    epochs: 150
    learning_rate: 0.001
    early_stopping_patience: 20
    reduce_lr_patience: 10

# Evaluation
evaluation:
  metrics:
    - 'accuracy'
    - 'precision'
    - 'recall'
    - 'f1'
    - 'auc'
  cv_folds: 10

# API settings
api:
  host: '0.0.0.0'
  port: 8000
  log_level: 'info'
  batch_size: 50
  max_workers: 4
  performance_logging: true

  # Caching settings
  caching:
    enabled: true
    max_size: 1000   # Maximum number of cached predictions
    ttl: 3600        # Time-to-live in seconds (1 hour)
    hash_algorithm: 'md5'  # Algorithm for generating cache keys

  # Authentication settings
  auth:
    # Set to false for automatic tests, true for production
    # ⚠️ IMPORTANT: Change to 'true' in production for security!
    enabled: false
    secret_key: 'YOUR_SECRET_KEY_HERE'  # Change this in production
    algorithm: 'HS256'
    access_token_expire_minutes: 30
    token_url: '/auth/token'

    # Default API key for testing/development. In production, use a secure key.
    api_keys:
      - key: 'dev_api_key'
        name: 'Development API Key'

    # Public endpoints (no authentication required)
    public_endpoints:
      - '/health'
      - '/docs'
      - '/redoc'
      - '/openapi.json'
      - '/auth/token'
