name: Fix Code Formatting

on:
  workflow_dispatch:

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install formatting tools
      run: |
        python -m pip install --upgrade pip
        pip install black isort

    - name: Format code with black
      run: |
        black src api tests

    - name: Sort imports with isort
      run: |
        isort --profile black src api tests

    - name: Create PR for code formatting
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "style: format code with black and isort"
        title: "Style: Format code with Black and isort"
        body: |
          ## Code Formatting

          This PR fixes code formatting issues that were causing CI/CD pipeline failures.

          - Applied Black formatting to all Python files
          - Sorted imports with isort

          This will fix the formatting check in the main CI/CD pipeline.
        branch: fix/code-formatting
        base: main
