name: Test & Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Lint with flake8
        run: |
          . .venv/bin/activate
          flake8 src/ tests/

      - name: Check formatting with black
        run: |
          . .venv/bin/activate
          black --check src/ tests/

      - name: Run tests with coverage
        run: |
          . .venv/bin/activate
          pytest --cov=src --cov-report=term-missing --cov-report=xml


      - name: Check formatting with black
        run: |
          . .venv/bin/activate
          black --check src/ tests/

      - name: Run tests with coverage
        run: |
          . .venv/bin/activate
          pytest --cov=src --cov-report=term-missing

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Only needed if repo is private
          files: coverage.xml
          fail_ci_if_error: true
